string drone_id
string drone_namespace
string boot_id
string state_topic
string navigate_action
string arm_service
string takeoff_action
bool has_lidar
bool supports_fixed_wing
bool supports_vtol
---
bool accepted
string message
float64 heartbeat_period_sec
float64 lease_timeout_sec
