uint8 CALCULATE=0
uint8 CLEAR_PENDING_TARGETS=1
uint8 CANCEL_ACTIVE_MISSION=2
uint8 RECALCULATE=3
uint8 RETURN_HOME=4

uint8 command
---
bool accepted
string message
uint32 pending_target_count
uint32 active_target_count
uint32 assigned_drone_count
